In [306]:
#Import all supported packages
%matplotlib inline 
#This line above helps plots to be seen in jupyter notebook, if we do not include this line, then plots should be shown as a pop-up window
import numpy as np #Package "numpy" is commonly used for dealing with numeric values
import pandas as pd #Package "pandas" is commonly used for dataframe cleaning, merging, etc
from matplotlib import pyplot #Package "matplotlib" is commonly used for data visualization, and the most widely used function is "pyplot"
from datetime import datetime #Package "datetime" is commonly used for re-formating date strings

In [307]:
#Import Arlo TS data using read_csv function in pandas
dir_to_data = "Price Prediction Time Series.xlsx" #Define the path of the data file
data_in_xlsx = pd.read_excel(dir_to_data,header=None) #Read the data file with no headers since we do not know the structure of the data file yet

In [308]:
#Take a look at the first 10 rows of the data using head() function in pandas
data_in_xlsx.head(n = 10)

,0,1,2,3,4,5,6,7,8,9,...,186,187,188,189,190,191,192,193,194,195
0,Security,SPX US Equity ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Start Date,1999-06-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,End Date,2019-06-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Period,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Currency,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,Date 1,S&P 500 US,NaN,Date 2,AAPLE US,NaN,...,NaN,Date 58,KOHNPW,NaN,Date 59,China Rice Imports Q/US,NaN,NaN,Date 60,USDA Corn Export
7,NaN,NaN,NaN,NaN,NaN,1342.84,NaN,NaN,1.683,NaN,...,NaN,NaN,104.044,NaN,NaN,430,NaN,NaN,NaN,1150.06
8,NaN,NaN,NaN,NaN,1999-06-25 00:00:00,1315.31,NaN,1999-06-25 00:00:00,1.5067,NaN,...,NaN,2016-02-16 00:00:00,103.962,NaN,2011-08-31 00:00:00,0,NaN,NaN,1999-06-24 00:00:00,1099.76
9,NaN,NaN,NaN,NaN,1999-07-02 00:00:00,1391.22,NaN,1999-07-02 00:00:00,1.654,NaN,...,NaN,2016-02-17 00:00:00,103.44,NaN,2011-09-30 00:00:00,0,NaN,NaN,1999-07-01 00:00:00,1212.24

In [309]:
#The data file is not clean, and the following bullet points discuss why it is not clean and how to deal with it:
#1. The first 6 rows of the raw data file should not be included, since they are not relevant to what we are investigating here. Solution: delete the first 6 rows
#2. The cell "Date 1", "S&P 500 US", "Date 2", etc. should be the actual headers
#3. There are columns with all values taking NaN between each group (e.g. there is a column like that between S&P5 500 US and Date 2). Solution: remove all columns with all values taking NaN

In [310]:
#1. Delete first 6 rows:
data_in_xlsx = data_in_xlsx[6:] #Take the 7th rows until the last row of data_in_xlsx, and then re-define data_in_xlsx. This is equivalent to deleting first 6 rows
#2. Let the row of "Date 1, S&P 500 US, ..." be the header
data_in_xlsx.columns = data_in_xlsx.iloc[0].values #The first row right now in data_in_xlsx is "Date 1, S&P 500 US, ...", and should be the header
data_in_xlsx = data_in_xlsx[1:] #Once the header is set, we should delete the row "Date 1, S&P 500 US, ..." since it is the header line, not a row in real time series
#3. Remove columns with all values taking NaN
data_in_xlsx = data_in_xlsx.dropna(axis = 1,how='all')

In [311]:
#Take a look at the first 10 rows of the data again
data_in_xlsx.head(n = 10)

,Date 1,S&P 500 US,Date 2,AAPLE US,Date 3,CPI Index US,Date 4,Big Mac Index US,Date 5,GDP % Change US,...,Date 56,Weapons NetTotal Return US,Date 57,CHGDNU,Date 58,KOHNPW,Date 59,China Rice Imports Q/US,Date 60,USDA Corn Export
7,NaN,1342.84,NaN,1.683,NaN,2,NaN,2.71,NaN,3.1,...,NaN,573,NaN,104.245,NaN,104.044,NaN,430,NaN,1150.06
8,1999-06-25 00:00:00,1315.31,1999-06-25 00:00:00,1.5067,1999-07-31 00:00:00,2.1,2000-12-31 00:00:00,2.38,1999-09-30 00:00:00,5.3,...,2006-06-01 00:00:00,573.79,2015-12-16 00:00:00,104.533,2016-02-16 00:00:00,103.962,2011-08-31 00:00:00,0,1999-06-24 00:00:00,1099.76
9,1999-07-02 00:00:00,1391.22,1999-07-02 00:00:00,1.654,1999-08-31 00:00:00,2.3,2001-12-31 00:00:00,2.27,1999-12-31 00:00:00,7,...,2006-06-02 00:00:00,585.43,2015-12-17 00:00:00,104.578,2016-02-17 00:00:00,103.44,2011-09-30 00:00:00,0,1999-07-01 00:00:00,1212.24
10,1999-07-09 00:00:00,1403.28,1999-07-09 00:00:00,1.9866,1999-09-30 00:00:00,2.6,2002-12-31 00:00:00,2.37,2000-03-31 00:00:00,1.5,...,2006-06-05 00:00:00,579.7,2015-12-18 00:00:00,104.604,2016-02-18 00:00:00,103.939,2011-11-30 00:00:00,0,1999-07-08 00:00:00,791.063
11,1999-07-16 00:00:00,1418.78,1999-07-16 00:00:00,1.8951,1999-10-31 00:00:00,2.6,2003-12-31 00:00:00,2.98,2000-06-30 00:00:00,7.5,...,2006-06-06 00:00:00,567.89,2015-12-21 00:00:00,104.677,2016-02-19 00:00:00,103.66,2012-10-31 00:00:00,7,1999-07-15 00:00:00,1146.27
12,1999-07-23 00:00:00,1356.94,1999-07-23 00:00:00,1.904,1999-11-30 00:00:00,2.6,2004-12-31 00:00:00,3.28,2000-09-30 00:00:00,0.5,...,2006-06-07 00:00:00,554.49,2015-12-22 00:00:00,104.814,2016-02-22 00:00:00,103.619,2013-04-30 00:00:00,0,1999-07-22 00:00:00,925.866
13,1999-07-30 00:00:00,1328.72,1999-07-30 00:00:00,1.9888,1999-12-31 00:00:00,2.7,2005-12-31 00:00:00,3.58,2000-12-31 00:00:00,2.5,...,2006-06-08 00:00:00,532.45,2015-12-23 00:00:00,104.867,2016-02-23 00:00:00,103.868,2013-06-30 00:00:00,0,1999-07-29 00:00:00,1254.1
14,1999-08-06 00:00:00,1300.29,1999-08-06 00:00:00,1.933,2000-01-31 00:00:00,2.7,2006-12-31 00:00:00,3.77,2001-03-31 00:00:00,-1.1,...,2006-06-09 00:00:00,539.14,2015-12-24 00:00:00,104.807,2016-02-24 00:00:00,103.741,2013-11-30 00:00:00,0,1999-08-05 00:00:00,1177.31
15,1999-08-13 00:00:00,1327.68,1999-08-13 00:00:00,2.1451,2000-02-29 00:00:00,3.2,2007-12-31 00:00:00,4.17,2001-06-30 00:00:00,2.4,...,2006-06-12 00:00:00,530.77,2015-12-25 00:00:00,104.814,2016-02-25 00:00:00,103.942,2014-02-28 00:00:00,260,1999-08-12 00:00:00,1124.27
16,1999-08-20 00:00:00,1336.61,1999-08-20 00:00:00,2.1138,2000-03-31 00:00:00,3.8,2008-12-31 00:00:00,5.34,2001-09-30 00:00:00,-1.7,...,2006-06-13 00:00:00,508.12,2015-12-28 00:00:00,104.736,2016-02-26 00:00:00,103.628,2014-04-30 00:00:00,0,1999-08-19 00:00:00,853.194

In [312]:
#Also notice that the first row now does not have a series of valid date, and this is due to data collection process, where the data were not saved as csv file. If the data were saved as xlsx file, then the bloomberg command (=bdh(...)) would still be saved, and would not give as a valid date in that case
#So we should delete the first row as well
data_in_xlsx = data_in_xlsx[1:]

In [313]:
#The dataframe data_in_xlsx is in clean format, and we should save this dataframe to csv for further use. Here we use function to_csv in pandas to save the file
dir_to_csv = 'Price Prediction Time Series Arlo Parker.csv'
data_in_xlsx.to_csv(dir_to_csv,index=False)

# Data merging

In [314]:
#Import the csv file which we just saved
data_in_csv = pd.read_csv(dir_to_csv)

In [315]:
#Take a look at the first 10 rows of the data
data_in_csv.head(n = 10)

,Date 1,S&P 500 US,Date 2,AAPLE US,Date 3,CPI Index US,Date 4,Big Mac Index US,Date 5,GDP % Change US,...,Date 56,Weapons NetTotal Return US,Date 57,CHGDNU,Date 58,KOHNPW,Date 59,China Rice Imports Q/US,Date 60,USDA Corn Export
0,1999-06-25 00:00:00,1315.31,1999-06-25 00:00:00,1.5067,1999-07-31 00:00:00,2.1,2000-12-31 00:00:00,2.38,1999-09-30 00:00:00,5.3,...,2006-06-01 00:00:00,573.79,2015-12-16 00:00:00,104.533,2016-02-16 00:00:00,103.962,2011-08-31 00:00:00,0.0,1999-06-24 00:00:00,1099.762
1,1999-07-02 00:00:00,1391.22,1999-07-02 00:00:00,1.6540,1999-08-31 00:00:00,2.3,2001-12-31 00:00:00,2.27,1999-12-31 00:00:00,7.0,...,2006-06-02 00:00:00,585.43,2015-12-17 00:00:00,104.578,2016-02-17 00:00:00,103.440,2011-09-30 00:00:00,0.0,1999-07-01 00:00:00,1212.237
2,1999-07-09 00:00:00,1403.28,1999-07-09 00:00:00,1.9866,1999-09-30 00:00:00,2.6,2002-12-31 00:00:00,2.37,2000-03-31 00:00:00,1.5,...,2006-06-05 00:00:00,579.70,2015-12-18 00:00:00,104.604,2016-02-18 00:00:00,103.939,2011-11-30 00:00:00,0.0,1999-07-08 00:00:00,791.063
3,1999-07-16 00:00:00,1418.78,1999-07-16 00:00:00,1.8951,1999-10-31 00:00:00,2.6,2003-12-31 00:00:00,2.98,2000-06-30 00:00:00,7.5,...,2006-06-06 00:00:00,567.89,2015-12-21 00:00:00,104.677,2016-02-19 00:00:00,103.660,2012-10-31 00:00:00,7.0,1999-07-15 00:00:00,1146.271
4,1999-07-23 00:00:00,1356.94,1999-07-23 00:00:00,1.9040,1999-11-30 00:00:00,2.6,2004-12-31 00:00:00,3.28,2000-09-30 00:00:00,0.5,...,2006-06-07 00:00:00,554.49,2015-12-22 00:00:00,104.814,2016-02-22 00:00:00,103.619,2013-04-30 00:00:00,0.0,1999-07-22 00:00:00,925.866
5,1999-07-30 00:00:00,1328.72,1999-07-30 00:00:00,1.9888,1999-12-31 00:00:00,2.7,2005-12-31 00:00:00,3.58,2000-12-31 00:00:00,2.5,...,2006-06-08 00:00:00,532.45,2015-12-23 00:00:00,104.867,2016-02-23 00:00:00,103.868,2013-06-30 00:00:00,0.0,1999-07-29 00:00:00,1254.098
6,1999-08-06 00:00:00,1300.29,1999-08-06 00:00:00,1.9330,2000-01-31 00:00:00,2.7,2006-12-31 00:00:00,3.77,2001-03-31 00:00:00,-1.1,...,2006-06-09 00:00:00,539.14,2015-12-24 00:00:00,104.807,2016-02-24 00:00:00,103.741,2013-11-30 00:00:00,0.0,1999-08-05 00:00:00,1177.311
7,1999-08-13 00:00:00,1327.68,1999-08-13 00:00:00,2.1451,2000-02-29 00:00:00,3.2,2007-12-31 00:00:00,4.17,2001-06-30 00:00:00,2.4,...,2006-06-12 00:00:00,530.77,2015-12-25 00:00:00,104.814,2016-02-25 00:00:00,103.942,2014-02-28 00:00:00,260.0,1999-08-12 00:00:00,1124.274
8,1999-08-20 00:00:00,1336.61,1999-08-20 00:00:00,2.1138,2000-03-31 00:00:00,3.8,2008-12-31 00:00:00,5.34,2001-09-30 00:00:00,-1.7,...,2006-06-13 00:00:00,508.12,2015-12-28 00:00:00,104.736,2016-02-26 00:00:00,103.628,2014-04-30 00:00:00,0.0,1999-08-19 00:00:00,853.194
9,1999-08-27 00:00:00,1348.27,1999-08-27 00:00:00,2.3125,2000-04-30 00:00:00,3.1,2009-12-31 00:00:00,4.62,2001-12-31 00:00:00,1.1,...,2006-06-14 00:00:00,514.27,2015-12-29 00:00:00,104.721,2016-02-29 00:00:00,103.695,2016-01-31 00:00:00,0.0,1999-08-26 00:00:00,1253.235

In [316]:
#To merge the data, we usually need a key column first to merge on. Here in this case, this key column should be a date column, and that date column should include any single date in this data file
#Therefore, we have to find all possible date in this data file. The methodology is to find all date values of all date columns first, and then remove the duplicates
#Combine the 1st, 3rd, 5th, ... columns, which are data columns
all_date_list = [] #List to restore all date values
for i in range(0,len(data_in_csv.columns.values)):
    if(i%2 == 0): #The index is an even number, then that column should be a date column
        all_date_list = all_date_list + data_in_csv.iloc[:,i].values.tolist()
#Find all unique date values (aka delete all duplicates) in the date list
unique_date_list = list(dict.fromkeys(all_date_list)) #Steps for removing duplicates: 1. transfer the list to dictionary. In dictionary, there is no duplicates. 2. transfer back to list
#Create a dataframe with date column as key column in merging
merge_data = pd.DataFrame()
merge_data['Date'] = unique_date_list

In [317]:
#Take a look at the first 10 rows of the merge_data dataframe
merge_data.head(n = 10)

                  Date
0  1999-06-25 00:00:00
1  1999-07-02 00:00:00
2  1999-07-09 00:00:00
3  1999-07-16 00:00:00
4  1999-07-23 00:00:00
5  1999-07-30 00:00:00
6  1999-08-06 00:00:00
7  1999-08-13 00:00:00
8  1999-08-20 00:00:00
9  1999-08-27 00:00:00

In [318]:
#We need to fix two things here: 1. delete the first row since this is no valid date values there
#                                2. make all the date values in order
#1. delete the first row since this is no valid date values there:
merge_data = merge_data[1:]
merge_data.reset_index(inplace=True) #As we have deleted the first date values, the index of this dataframe has been changed, and we have to reset it
merge_data = merge_data.drop("index",axis = 1) #When we do reset_index(), there is another column "index" created, and we have to delete this column
#2. make all the date values in order
type(merge_data['Date'][1]) == str #we first know that each date value in the date column in actually a string, this means that we cannot order the date values right now since the machine does not know they are dates
#Therefore, the methodology here is to make another column "date_in_datetime_format" in this merge_data dataframe, and then we rank the dataframe based on the "date_in_datetime_format" column
merge_data

                     Date
0     1999-07-02 00:00:00
1     1999-07-09 00:00:00
2     1999-07-16 00:00:00
3     1999-07-23 00:00:00
4     1999-07-30 00:00:00
5     1999-08-06 00:00:00
6     1999-08-13 00:00:00
7     1999-08-20 00:00:00
8     1999-08-27 00:00:00
9     1999-09-03 00:00:00
10    1999-09-10 00:00:00
11    1999-09-17 00:00:00
12    1999-09-24 00:00:00
13    1999-10-01 00:00:00
14    1999-10-08 00:00:00
15    1999-10-15 00:00:00
16    1999-10-22 00:00:00
17    1999-10-29 00:00:00
18    1999-11-05 00:00:00
19    1999-11-12 00:00:00
20    1999-11-19 00:00:00
21    1999-11-26 00:00:00
22    1999-12-03 00:00:00
23    1999-12-10 00:00:00
24    1999-12-17 00:00:00
25    1999-12-24 00:00:00
26    1999-12-31 00:00:00
27    2000-01-07 00:00:00
28    2000-01-14 00:00:00
29    2000-01-21 00:00:00
...                   ...
5251  2007-05-28 00:00:00
5252  2007-07-04 00:00:00
5253  2007-09-03 00:00:00
5254  2007-12-25 00:00:00
5255  2008-01-01 00:00:00
5256  2008-01-21 00:00:00
5257  2008-02-18 00:00:00
5258  2008-05-26 00:00:00
5259  2008-09-01 00:00:00
5260  2009-01-19 00:00:00
5261  2009-02-16 00:00:00
5262  2009-05-25 00:00:00
5263  2009-09-07 00:00:00
5264  2010-01-18 00:00:00
5265  2010-02-15 00:00:00
5266  2010-07-05 00:00:00
5267  2011-01-17 00:00:00
5268  2011-05-30 00:00:00
5269  2011-07-04 00:00:00
5270  2012-01-16 00:00:00
5271  2012-12-25 00:00:00
5272  2013-01-01 00:00:00
5273  2013-01-21 00:00:00
5274  2013-02-18 00:00:00
5275  2002-01-01 00:00:00
5276  2007-01-01 00:00:00
5277  2010-09-06 00:00:00
5278  2011-02-21 00:00:00
5279  2011-09-05 00:00:00
5280  2011-12-26 00:00:00

[5281 rows x 1 columns]

In [319]:
#creating a temporary column for merged dates
merge_data['date_in_datetime_format'] = pd.to_datetime(merge_data["Date"], format="%Y-%m-%d %H:%M:%S")

In [320]:
merge_data['date_in_datetime_format']

0      1999-07-02
1      1999-07-09
2      1999-07-16
3      1999-07-23
4      1999-07-30
5      1999-08-06
6      1999-08-13
7      1999-08-20
8      1999-08-27
9      1999-09-03
10     1999-09-10
11     1999-09-17
12     1999-09-24
13     1999-10-01
14     1999-10-08
15     1999-10-15
16     1999-10-22
17     1999-10-29
18     1999-11-05
19     1999-11-12
20     1999-11-19
21     1999-11-26
22     1999-12-03
23     1999-12-10
24     1999-12-17
25     1999-12-24
26     1999-12-31
27     2000-01-07
28     2000-01-14
29     2000-01-21
          ...
5251   2007-05-28
5252   2007-07-04
5253   2007-09-03
5254   2007-12-25
5255   2008-01-01
5256   2008-01-21
5257   2008-02-18
5258   2008-05-26
5259   2008-09-01
5260   2009-01-19
5261   2009-02-16
5262   2009-05-25
5263   2009-09-07
5264   2010-01-18
5265   2010-02-15
5266   2010-07-05
5267   2011-01-17
5268   2011-05-30
5269   2011-07-04
5270   2012-01-16
5271   2012-12-25
5272   2013-01-01
5273   2013-01-21
5274   2013-02-18
5275   2002-01-01
5276   2007-01-01
5277   2010-09-06
5278   2011-02-21
5279   2011-09-05
5280   2011-12-26
Name: date_in_datetime_format, dtype: datetime64[ns]

In [321]:
merge_data = merge_data.sort_values(by='date_in_datetime_format',ascending=True) #Sort the dataframe by column "date_in_datetime_format"
merge_data = merge_data.reset_index() #Sorting will change the index, so we have to reset index here
merge_data.drop('index',axis=1,inplace=True)
#We then delete the column "date_in_datetime_format" since it has finished its job
merge_data.drop('date_in_datetime_format',axis=1,inplace=True)

In [322]:
merge_data

                     Date
0     1999-06-15 00:00:00
1     1999-06-16 00:00:00
2     1999-06-17 00:00:00
3     1999-06-18 00:00:00
4     1999-06-21 00:00:00
5     1999-06-22 00:00:00
6     1999-06-23 00:00:00
7     1999-06-24 00:00:00
8     1999-06-28 00:00:00
9     1999-06-29 00:00:00
10    1999-06-30 00:00:00
11    1999-07-01 00:00:00
12    1999-07-02 00:00:00
13    1999-07-05 00:00:00
14    1999-07-06 00:00:00
15    1999-07-07 00:00:00
16    1999-07-08 00:00:00
17    1999-07-09 00:00:00
18    1999-07-12 00:00:00
19    1999-07-13 00:00:00
20    1999-07-14 00:00:00
21    1999-07-15 00:00:00
22    1999-07-16 00:00:00
23    1999-07-19 00:00:00
24    1999-07-20 00:00:00
25    1999-07-21 00:00:00
26    1999-07-22 00:00:00
27    1999-07-23 00:00:00
28    1999-07-26 00:00:00
29    1999-07-27 00:00:00
...                   ...
5251  2019-04-30 00:00:00
5252  2019-05-01 00:00:00
5253  2019-05-02 00:00:00
5254  2019-05-03 00:00:00
5255  2019-05-06 00:00:00
5256  2019-05-07 00:00:00
5257  2019-05-08 00:00:00
5258  2019-05-09 00:00:00
5259  2019-05-10 00:00:00
5260  2019-05-13 00:00:00
5261  2019-05-14 00:00:00
5262  2019-05-15 00:00:00
5263  2019-05-16 00:00:00
5264  2019-05-17 00:00:00
5265  2019-05-20 00:00:00
5266  2019-05-21 00:00:00
5267  2019-05-22 00:00:00
5268  2019-05-23 00:00:00
5269  2019-05-24 00:00:00
5270  2019-05-27 00:00:00
5271  2019-05-28 00:00:00
5272  2019-05-29 00:00:00
5273  2019-05-30 00:00:00
5274  2019-05-31 00:00:00
5275  2019-06-03 00:00:00
5276  2019-06-04 00:00:00
5277  2019-06-05 00:00:00
5278  2019-06-06 00:00:00
5279  2019-06-07 00:00:00
5280                  NaN

[5281 rows x 1 columns]

In [323]:
#Then we need to merge all the data based on the "Date" column in merge_data dataframe
#The methodology is simple. Each time we feed in a group of time series (date column + real value column), and we merge based on the date column. After merging, we delete the orginal date column, and only keep the key date column we just created
for i in range(0,len(data_in_csv.columns.values)):
    if(i%2 == 0): #The index is an even number, then that column should be a date column, and that is how we define the start index of a group (date ts + real value ts)
        temp_data = data_in_csv.iloc[:,i:(i+2)] #Each time, take the group out and save them as temp_data dataframe
        temp_data = temp_data.dropna(axis = 0) #Drop the rows with NaN values in temp_data dataframe
        merge_data = pd.merge(merge_data,temp_data,how='left',left_on='Date',right_on=temp_data.columns.values[0]) #Merge the merge_data and temp_data based on their date column
        merge_data.drop(temp_data.columns.values[0],axis=1,inplace=True) #Remove the date column generated by temp_data

In [324]:
#Take a look at the first 10 rows of the current merge_data dataframe
merge_data

,Date,S&P 500 US,AAPLE US,CPI Index US,Big Mac Index US,GDP % Change US,Goods Index US,GDP Pers. Cons. US,GDP PIQQ Index,T. Gross Pr. Dom Invest. US,...,LNG US,LNG Export US,LNG China/US,Weapons X US,LNG AU Equity,Weapons NetTotal Return US,CHGDNU,KOHNPW,China Rice Imports Q/US,USDA Corn Export
0,1999-06-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1999-06-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1999-06-17 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1999-06-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1999-06-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1999-06-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1999-06-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1999-06-24 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1099.762
8,1999-06-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1999-06-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.7500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1999-06-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.7500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1999-07-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1212.237
12,1999-07-02 00:00:00,1391.22,1.6540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1999-07-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1999-07-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1999-07-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1999-07-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,791.063
17,1999-07-09 00:00:00,1403.28,1.9866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.8750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1999-07-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.9375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1999-07-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1999-07-14 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.9375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1999-07-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.5625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1146.271
22,1999-07-16 00:00:00,1418.78,1.8951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.6250,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1999-07-19 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.9375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1999-07-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1999-07-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.7500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1999-07-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.7500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,925.866
27,1999-07-23 00:00:00,1356.94,1.9040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.3125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1999-07-26 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.2500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1999-07-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.3750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5251,2019-04-30 00:00:00,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,64.3500,NaN,65628.0,121.0,0.435,1117.60,100.624,100.212,NaN,NaN
5252,2019-05-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,64.4500,NaN,NaN,NaN,0.435,1118.93,NaN,100.095,NaN,NaN
5253,2019-05-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,64.2500,NaN,NaN,NaN,0.440,1117.46,NaN,99.971,NaN,976.842
5254,2019-05-03 00:00:00,2945.64,211.7500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,64.4700,NaN,NaN,NaN,0.440,1121.57,NaN,100.071,NaN,NaN
5255,2019-05-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,64.3200,NaN,NaN,NaN,0.420,1100.75,100.714,100.211,NaN,NaN
5256,2019-05-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.2400,NaN,NaN,NaN,0.415,1095.14,100.644,100.202,NaN,NaN
5257,2019-05-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63.8400,NaN,NaN,NaN,0.415,1088.92,100.612,100.116,NaN,NaN
5258,2019-05-09 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,64.9700,NaN,NaN,NaN,0.410,1065.57,100.603,100.185,NaN,1000.834
5259,2019-05-10 00:00:00,2881.40,197.1800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67.8700,NaN,NaN,NaN,0.410,1070.82,100.607,100.171,NaN,NaN
5260,2019-05-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.6400,NaN,NaN,NaN,0.410,1053.37,100.623,100.484,NaN,NaN
5261,2019-05-14 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67.1100,NaN,NaN,NaN,0.385,1051.26,100.620,100.434,NaN,NaN
5262,2019-05-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67.0200,NaN,NaN,NaN,0.400,1052.84,100.617,100.566,NaN,NaN
5263,2019-05-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67.8100,NaN,NaN,NaN,0.395,1047.86,100.610,100.458,NaN,840.474
5264,2019-05-17 00:00:00,2859.53,189.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67.2100,NaN,NaN,NaN,0.385,1032.68,100.605,100.428,NaN,NaN
5265,2019-05-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,66.4000,NaN,NaN,NaN,0.385,1030.16,100.590,100.329,NaN,NaN
5266,2019-05-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67.1400,NaN,NaN,NaN,0.380,1035.37,100.586,100.239,NaN,NaN
5267,2019-05-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,66.5600,NaN,NaN,NaN,0.375,1034.51,100.589,100.348,NaN,NaN
5268,2019-05-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,64.8900,NaN,NaN,NaN,0.365,1021.44,100.583,100.583,NaN,1108.727
5269,2019-05-24 00:00:00,2826.06,178.9700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,64.5600,NaN,NaN,NaN,0.350,1023.42,100.587,100.595,NaN,NaN
5270,2019-05-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.340,1026.23,100.586,NaN,NaN,NaN
5271,2019-05-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,62.5800,NaN,NaN,NaN,0.330,1025.34,100.583,100.582,NaN,NaN
5272,2019-05-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63.9500,NaN,NaN,NaN,0.310,1022.63,100.549,100.601,NaN,NaN
5273,2019-05-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63.0100,NaN,NaN,NaN,0.285,1032.58,100.564,100.750,NaN,743.077
5274,2019-05-31 00:00:00,2752.06,175.0700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63.1800,NaN,NaN,NaN,0.305,1036.02,100.561,101.087,NaN,NaN
5275,2019-06-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,64.7400,NaN,NaN,NaN,0.280,1047.00,100.563,101.408,NaN,NaN
5276,2019-06-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,66.1400,NaN,NaN,NaN,0.290,1044.13,100.564,101.230,NaN,NaN
5277,2019-06-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.7500,NaN,NaN,NaN,0.275,1043.74,100.565,101.278,NaN,NaN
5278,2019-06-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67.2400,NaN,NaN,NaN,0.260,1041.93,100.567,101.176,NaN,NaN
5279,2019-06-07 00:00:00,2878.27,190.3700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,67.6000,NaN,NaN,NaN,0.260,NaN,NaN,101.343,NaN,NaN
5280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [325]:
#saving a merged data to a new csv file named 'merge_data.csv'
dir_to_csv = 'merge_data.csv'
merge_data.to_csv(dir_to_csv,index=False)

In [326]:
#reading data from csv
data_monthly = pd.read_csv(dir_to_csv)

In [327]:
#creating date_in_months column which carry the year and month of each date
data_monthly['date_in_months'] = pd.to_datetime(data_monthly["Date"], format="%Y-%m")
data_monthly['date_in_months'] = data_monthly['date_in_months'].dt.strftime('%Y-%m')

In [328]:
data_monthly

,Date,S&P 500 US,AAPLE US,CPI Index US,Big Mac Index US,GDP % Change US,Goods Index US,GDP Pers. Cons. US,GDP PIQQ Index,T. Gross Pr. Dom Invest. US,...,LNG Export US,LNG China/US,Weapons X US,LNG AU Equity,Weapons NetTotal Return US,CHGDNU,KOHNPW,China Rice Imports Q/US,USDA Corn Export,date_in_months
0,1999-06-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
1,1999-06-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
2,1999-06-17 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
3,1999-06-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
4,1999-06-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
5,1999-06-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
6,1999-06-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
7,1999-06-24 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1099.762,1999-06
8,1999-06-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
9,1999-06-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
10,1999-06-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
11,1999-07-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1212.237,1999-07
12,1999-07-02 00:00:00,1391.22,1.6540,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-07
13,1999-07-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-07
14,1999-07-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-07
15,1999-07-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-07
16,1999-07-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,791.063,1999-07
17,1999-07-09 00:00:00,1403.28,1.9866,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-07
18,1999-07-12 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-07
19,1999-07-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-07
20,1999-07-14 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-07
21,1999-07-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1146.271,1999-07
22,1999-07-16 00:00:00,1418.78,1.8951,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-07
23,1999-07-19 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-07
24,1999-07-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-07
25,1999-07-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-07
26,1999-07-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,925.866,1999-07
27,1999-07-23 00:00:00,1356.94,1.9040,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-07
28,1999-07-26 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-07
29,1999-07-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5251,2019-04-30 00:00:00,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,65628.0,121.0,0.435,1117.60,100.624,100.212,NaN,NaN,2019-04
5252,2019-05-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.435,1118.93,NaN,100.095,NaN,NaN,2019-05
5253,2019-05-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.440,1117.46,NaN,99.971,NaN,976.842,2019-05
5254,2019-05-03 00:00:00,2945.64,211.7500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.440,1121.57,NaN,100.071,NaN,NaN,2019-05
5255,2019-05-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.420,1100.75,100.714,100.211,NaN,NaN,2019-05
5256,2019-05-07 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.415,1095.14,100.644,100.202,NaN,NaN,2019-05
5257,2019-05-08 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.415,1088.92,100.612,100.116,NaN,NaN,2019-05
5258,2019-05-09 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.410,1065.57,100.603,100.185,NaN,1000.834,2019-05
5259,2019-05-10 00:00:00,2881.40,197.1800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.410,1070.82,100.607,100.171,NaN,NaN,2019-05
5260,2019-05-13 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.410,1053.37,100.623,100.484,NaN,NaN,2019-05
5261,2019-05-14 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.385,1051.26,100.620,100.434,NaN,NaN,2019-05
5262,2019-05-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.400,1052.84,100.617,100.566,NaN,NaN,2019-05
5263,2019-05-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.395,1047.86,100.610,100.458,NaN,840.474,2019-05
5264,2019-05-17 00:00:00,2859.53,189.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.385,1032.68,100.605,100.428,NaN,NaN,2019-05
5265,2019-05-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.385,1030.16,100.590,100.329,NaN,NaN,2019-05
5266,2019-05-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.380,1035.37,100.586,100.239,NaN,NaN,2019-05
5267,2019-05-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.375,1034.51,100.589,100.348,NaN,NaN,2019-05
5268,2019-05-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.365,1021.44,100.583,100.583,NaN,1108.727,2019-05
5269,2019-05-24 00:00:00,2826.06,178.9700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.350,1023.42,100.587,100.595,NaN,NaN,2019-05
5270,2019-05-27 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.340,1026.23,100.586,NaN,NaN,NaN,2019-05
5271,2019-05-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.330,1025.34,100.583,100.582,NaN,NaN,2019-05
5272,2019-05-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.310,1022.63,100.549,100.601,NaN,NaN,2019-05
5273,2019-05-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.285,1032.58,100.564,100.750,NaN,743.077,2019-05
5274,2019-05-31 00:00:00,2752.06,175.0700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.305,1036.02,100.561,101.087,NaN,NaN,2019-05
5275,2019-06-03 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.280,1047.00,100.563,101.408,NaN,NaN,2019-06
5276,2019-06-04 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.290,1044.13,100.564,101.230,NaN,NaN,2019-06
5277,2019-06-05 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.275,1043.74,100.565,101.278,NaN,NaN,2019-06
5278,2019-06-06 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.260,1041.93,100.567,101.176,NaN,NaN,2019-06
5279,2019-06-07 00:00:00,2878.27,190.3700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.260,NaN,NaN,101.343,NaN,NaN,2019-06
5280,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

In [329]:
#giving all the data which carry the same month and year as at index 0
data_monthly.loc[data_monthly['date_in_months'] == data_monthly['date_in_months'][0]]

,Date,S&P 500 US,AAPLE US,CPI Index US,Big Mac Index US,GDP % Change US,Goods Index US,GDP Pers. Cons. US,GDP PIQQ Index,T. Gross Pr. Dom Invest. US,...,LNG Export US,LNG China/US,Weapons X US,LNG AU Equity,Weapons NetTotal Return US,CHGDNU,KOHNPW,China Rice Imports Q/US,USDA Corn Export,date_in_months
0,1999-06-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
1,1999-06-16 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
2,1999-06-17 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
3,1999-06-18 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
4,1999-06-21 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
5,1999-06-22 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
6,1999-06-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
7,1999-06-24 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1099.762,1999-06
8,1999-06-28 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
9,1999-06-29 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06
10,1999-06-30 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999-06

In [330]:
#minimun date in the date_in_months column
data_monthly['date_in_months'].min()

'1999-06'

In [331]:
#maximun date in the date_in_months column it give nan because we have nan value in the last of this column

data_monthly['date_in_months'].max()

'NaT'

In [332]:
#elemenating the last row
data_monthly = data_monthly[:5280]

In [333]:
#now this wil give us the correct maximum date
data_monthly['date_in_months'].max()

'2019-06'

In [334]:
#taking mean for each column where date_in_months value is same

final=data_monthly.groupby('date_in_months').mean()
final

,S&P 500 US,AAPLE US,CPI Index US,Big Mac Index US,GDP % Change US,Goods Index US,GDP Pers. Cons. US,GDP PIQQ Index,T. Gross Pr. Dom Invest. US,Total Gov-t Cons. Exp. US,...,LNG US,LNG Export US,LNG China/US,Weapons X US,LNG AU Equity,Weapons NetTotal Return US,CHGDNU,KOHNPW,China Rice Imports Q/US,USDA Corn Export
date_in_months,,,,,,,,,,,,,,,,,,,,,
1999-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.892045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1099.76200
1999-07,1379.7880,1.885700,2.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.328125,5.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1065.90700
1999-08,1328.2125,2.126100,2.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.058241,5.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1102.00350
1999-09,1330.4200,2.614400,2.6,NaN,5.3,4.8,4.5,1.5,-0.5,4.4,...,2.734375,5.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1116.68380
1999-10,1306.1640,2.542160,2.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.373514,3.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,979.25925
1999-11,1401.2275,3.271750,2.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.375000,5.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,886.09500
1999-12,1439.7920,3.745080,2.7,NaN,7.0,7.0,5.4,2.1,1.3,4.8,...,1.000000,5.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,960.54400
2000-01,1427.0350,3.686400,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.696875,5.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,935.36675
2000-02,1372.7350,3.914050,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.387500,5.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,882.84350
2000-03,1458.9500,4.666060,3.8,NaN,1.5,6.1,6.4,2.8,2.4,4.8,...,2.164404,3.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,859.22940
2000-04,1439.9700,4.344300,3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.297700,5.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,915.10925
2000-05,1409.6400,3.581475,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.470177,5.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,858.28725
2000-06,1458.9500,3.483040,3.7,NaN,7.5,2.1,5.0,2.4,1.5,3.3,...,1.490059,3.79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,775.14180
2000-07,1472.2400,3.821425,3.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.490625,5.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,890.24775
2000-08,1483.2350,3.604900,3.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.562500,5.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1051.52020
2000-09,1473.2620,3.649800,3.5,NaN,0.5,4.2,3.8,2.5,1.7,3.8,...,1.579690,5.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1199.32125
2000-10,1389.9175,1.469875,3.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.111514,7.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,954.68375
2000-11,1375.5400,1.412950,3.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.978438,5.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,813.18260
2000-12,1324.7040,1.086620,3.4,2.38,2.5,3.5,3.5,2.1,0.7,3.9,...,1.154100,5.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,774.57800
2001-01,1328.5400,1.296875,3.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.151795,5.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,713.86975
2001-02,1302.9050,1.385050,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.465174,3.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,888.75550
2001-03,1183.6580,1.488500,2.9,NaN,-1.1,0.9,2.0,2.6,0.2,3.4,...,1.404832,5.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,948.15340
2001-04,1201.9900,1.683025,3.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.248250,5.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,955.26175
2001-05,1270.5325,1.694450,3.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.198636,5.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,629.20300
2001-06,1237.9520,1.545140,3.2,NaN,2.4,1.1,0.9,2.7,1.1,1.8,...,1.064524,3.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,871.27975
2001-07,1205.7350,1.532500,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.983810,5.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1055.38625
2001-08,1176.9980,1.338720,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.883158,5.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1142.68940
2001-09,1046.2650,1.176625,2.6,NaN,-1.7,2.9,0.6,1.3,1.1,1.6,...,0.645000,5.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1050.81400
2001-10,1085.2800,1.270000,2.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.502727,7.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,819.15675
2001-11,1127.1900,1.391260,1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.506190,5.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,758.40760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-01,2279.4050,119.725000,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,44.805000,51.34,130906.0,171.0,0.805250,879.515000,101.841444,NaN,0.0,959.89525
2017-02,2333.0050,133.395000,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,47.995263,52.04,67400.0,240.0,0.807750,919.767000,101.565333,NaN,0.0,1255.21300
2017-03,2368.1340,140.642000,2.4,NaN,1.8,1.9,1.7,2.0,1.0,3.7,...,45.696087,43.55,136914.0,183.0,0.673043,938.871304,101.255696,NaN,1.0,1486.16640
2017-04,2354.3450,142.577500,2.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,46.741053,50.67,65367.0,288.0,0.666176,953.296500,101.145111,NaN,0.0,1287.31325
2017-05,2396.9350,152.932500,1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.099545,60.78,0.0,178.0,0.681957,988.126957,100.143500,NaN,0.0,1164.02325
2017-06,2433.1400,147.400000,1.6,NaN,3.0,5.6,1.7,1.2,2.0,1.6,...,48.134091,52.46,63076.0,400.0,0.611429,1003.840455,100.276455,NaN,2.0,1113.45380
2017-07,2457.2725,148.247500,1.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,46.754000,53.59,0.0,494.0,0.617381,1038.293333,100.609095,100.859000,1.0,1027.51925
2017-08,2446.6875,157.807500,1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,42.453913,45.47,139423.0,224.0,0.563696,1069.774348,100.678478,101.212652,1.0,824.87360
2017-09,2491.9580,157.714000,2.2,NaN,2.8,4.1,1.4,2.2,1.9,2.5,...,43.633000,54.73,0.0,554.0,0.471667,1096.326667,100.491524,100.199000,3.0,749.90150
2017-10,2564.6950,157.897500,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,46.328182,80.19,259417.0,539.0,0.431364,1116.380909,100.174294,100.054619,0.0,516.60300
2017-11,2587.8525,173.072500,2.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.666667,80.10,407325.0,376.0,0.471818,1138.683636,99.667818,100.031000,1.0,558.10040
2017-12,2665.2960,171.726000,2.1,4.47,2.3,6.8,2.6,2.5,1.3,3.2,...,49.880000,82.60,259262.0,455.0,0.430263,1131.860000,99.316095,99.715600,0.0,675.52575
2018-01,2803.1400,175.515000,2.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,55.990000,72.46,506485.0,291.0,0.565238,1229.062609,99.241409,99.203143,4.0,802.19900
2018-02,2715.3000,166.210000,2.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56.116842,73.68,255101.0,199.0,0.497000,1203.389500,99.383267,98.346526,0.0,1049.93000
2018-03,2691.7920,173.386000,2.4,NaN,2.2,-0.6,1.0,2.0,2.5,2.9,...,53.247619,91.54,126019.0,251.0,0.462619,1205.276818,99.290773,97.919429,0.0,1314.41440
2018-04,2650.2050,167.787500,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56.527619,85.68,205696.0,229.0,0.436053,1176.425238,100.354833,97.348429,0.0,1684.08900
2018-05,2706.3600,186.827500,2.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,62.424091,94.80,395656.0,938.0,0.436739,1155.392174,100.161182,96.953611,0.0,1657.07160
2018-06,2753.3120,188.162000,2.9,NaN,4.2,5.5,3.0,3.0,3.1,3.3,...,65.685714,73.54,136137.0,317.0,0.519750,1124.274286,99.746150,97.096810,0.0,1542.47075
2018-07,2795.4450,190.430000,2.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63.418095,98.24,58854.0,202.0,0.592273,1094.585909,99.979364,96.915524,NaN,1429.34675
2018-08,2859.9940,215.378000,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63.386522,91.53,195771.0,207.0,0.764348,1081.581739,101.161696,97.339217,NaN,1249.34000
2018-09,2905.0775,222.135000,2.3,NaN,3.4,4.3,3.2,1.8,2.0,2.5,...,66.864211,81.38,136694.0,202.0,0.653250,1056.427000,101.283684,97.154789,NaN,1137.45575
2018-10,2769.7925,220.502500,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63.803478,89.89,0.0,434.0,0.589783,1006.529565,101.139111,96.979636,NaN,1029.67650
2018-11,2726.6140,191.270000,2.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,60.775714,107.58,138892.0,453.0,0.490682,1009.740455,101.015364,97.239250,NaN,1106.70040
2018-12,2533.8475,160.232500,1.9,4.74,2.2,2.6,2.4,1.7,1.4,2.6,...,59.643684,122.80,0.0,257.0,0.491316,999.727619,100.985900,98.023000,NaN,928.01375
2019-01,2615.9175,153.782500,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63.873333,126.96,135017.0,419.0,0.541429,1033.740000,101.090636,98.491095,NaN,902.52680
2019-02,2745.6700,170.080000,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.776842,102.87,67047.0,380.0,0.484750,1080.801000,101.029800,98.890526,NaN,830.12675
2019-03,2800.8700,183.000000,1.9,NaN,3.1,-0.3,2.1,0.8,1.6,1.1,...,67.538095,130.81,NaN,318.0,0.477857,1088.688571,100.838714,99.576524,NaN,965.49800
2019-04,2911.2650,201.007500,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,66.479048,NaN,65628.0,121.0,0.446316,1123.583182,100.737667,100.023667,NaN,1241.92800
2019-05,2852.9380,190.394000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.294091,NaN,NaN,NaN,0.381957,1056.733478,100.601650,100.386636,NaN,933.99080
2019-06,2878.2700,190.370000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,66.294000,NaN,NaN,NaN,0.273000,1044.200000,100.564750,101.287000,NaN,NaN

In [335]:
#saving to final csv
dir_to_csv = 'final.csv'
final.to_csv(dir_to_csv)

In [336]:
final

,S&P 500 US,AAPLE US,CPI Index US,Big Mac Index US,GDP % Change US,Goods Index US,GDP Pers. Cons. US,GDP PIQQ Index,T. Gross Pr. Dom Invest. US,Total Gov-t Cons. Exp. US,...,LNG US,LNG Export US,LNG China/US,Weapons X US,LNG AU Equity,Weapons NetTotal Return US,CHGDNU,KOHNPW,China Rice Imports Q/US,USDA Corn Export
date_in_months,,,,,,,,,,,,,,,,,,,,,
1999-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.892045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1099.76200
1999-07,1379.7880,1.885700,2.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.328125,5.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1065.90700
1999-08,1328.2125,2.126100,2.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.058241,5.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1102.00350
1999-09,1330.4200,2.614400,2.6,NaN,5.3,4.8,4.5,1.5,-0.5,4.4,...,2.734375,5.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1116.68380
1999-10,1306.1640,2.542160,2.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.373514,3.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,979.25925
1999-11,1401.2275,3.271750,2.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.375000,5.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,886.09500
1999-12,1439.7920,3.745080,2.7,NaN,7.0,7.0,5.4,2.1,1.3,4.8,...,1.000000,5.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,960.54400
2000-01,1427.0350,3.686400,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.696875,5.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,935.36675
2000-02,1372.7350,3.914050,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.387500,5.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,882.84350
2000-03,1458.9500,4.666060,3.8,NaN,1.5,6.1,6.4,2.8,2.4,4.8,...,2.164404,3.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,859.22940
2000-04,1439.9700,4.344300,3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.297700,5.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,915.10925
2000-05,1409.6400,3.581475,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.470177,5.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,858.28725
2000-06,1458.9500,3.483040,3.7,NaN,7.5,2.1,5.0,2.4,1.5,3.3,...,1.490059,3.79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,775.14180
2000-07,1472.2400,3.821425,3.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.490625,5.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,890.24775
2000-08,1483.2350,3.604900,3.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.562500,5.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1051.52020
2000-09,1473.2620,3.649800,3.5,NaN,0.5,4.2,3.8,2.5,1.7,3.8,...,1.579690,5.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1199.32125
2000-10,1389.9175,1.469875,3.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.111514,7.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,954.68375
2000-11,1375.5400,1.412950,3.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.978438,5.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,813.18260
2000-12,1324.7040,1.086620,3.4,2.38,2.5,3.5,3.5,2.1,0.7,3.9,...,1.154100,5.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,774.57800
2001-01,1328.5400,1.296875,3.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.151795,5.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,713.86975
2001-02,1302.9050,1.385050,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.465174,3.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,888.75550
2001-03,1183.6580,1.488500,2.9,NaN,-1.1,0.9,2.0,2.6,0.2,3.4,...,1.404832,5.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,948.15340
2001-04,1201.9900,1.683025,3.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.248250,5.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,955.26175
2001-05,1270.5325,1.694450,3.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.198636,5.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,629.20300
2001-06,1237.9520,1.545140,3.2,NaN,2.4,1.1,0.9,2.7,1.1,1.8,...,1.064524,3.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,871.27975
2001-07,1205.7350,1.532500,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.983810,5.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1055.38625
2001-08,1176.9980,1.338720,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.883158,5.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1142.68940
2001-09,1046.2650,1.176625,2.6,NaN,-1.7,2.9,0.6,1.3,1.1,1.6,...,0.645000,5.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1050.81400
2001-10,1085.2800,1.270000,2.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.502727,7.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,819.15675
2001-11,1127.1900,1.391260,1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.506190,5.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,758.40760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-01,2279.4050,119.725000,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,44.805000,51.34,130906.0,171.0,0.805250,879.515000,101.841444,NaN,0.0,959.89525
2017-02,2333.0050,133.395000,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,47.995263,52.04,67400.0,240.0,0.807750,919.767000,101.565333,NaN,0.0,1255.21300
2017-03,2368.1340,140.642000,2.4,NaN,1.8,1.9,1.7,2.0,1.0,3.7,...,45.696087,43.55,136914.0,183.0,0.673043,938.871304,101.255696,NaN,1.0,1486.16640
2017-04,2354.3450,142.577500,2.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,46.741053,50.67,65367.0,288.0,0.666176,953.296500,101.145111,NaN,0.0,1287.31325
2017-05,2396.9350,152.932500,1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.099545,60.78,0.0,178.0,0.681957,988.126957,100.143500,NaN,0.0,1164.02325
2017-06,2433.1400,147.400000,1.6,NaN,3.0,5.6,1.7,1.2,2.0,1.6,...,48.134091,52.46,63076.0,400.0,0.611429,1003.840455,100.276455,NaN,2.0,1113.45380
2017-07,2457.2725,148.247500,1.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,46.754000,53.59,0.0,494.0,0.617381,1038.293333,100.609095,100.859000,1.0,1027.51925
2017-08,2446.6875,157.807500,1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,42.453913,45.47,139423.0,224.0,0.563696,1069.774348,100.678478,101.212652,1.0,824.87360
2017-09,2491.9580,157.714000,2.2,NaN,2.8,4.1,1.4,2.2,1.9,2.5,...,43.633000,54.73,0.0,554.0,0.471667,1096.326667,100.491524,100.199000,3.0,749.90150
2017-10,2564.6950,157.897500,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,46.328182,80.19,259417.0,539.0,0.431364,1116.380909,100.174294,100.054619,0.0,516.60300
2017-11,2587.8525,173.072500,2.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,48.666667,80.10,407325.0,376.0,0.471818,1138.683636,99.667818,100.031000,1.0,558.10040
2017-12,2665.2960,171.726000,2.1,4.47,2.3,6.8,2.6,2.5,1.3,3.2,...,49.880000,82.60,259262.0,455.0,0.430263,1131.860000,99.316095,99.715600,0.0,675.52575
2018-01,2803.1400,175.515000,2.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,55.990000,72.46,506485.0,291.0,0.565238,1229.062609,99.241409,99.203143,4.0,802.19900
2018-02,2715.3000,166.210000,2.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56.116842,73.68,255101.0,199.0,0.497000,1203.389500,99.383267,98.346526,0.0,1049.93000
2018-03,2691.7920,173.386000,2.4,NaN,2.2,-0.6,1.0,2.0,2.5,2.9,...,53.247619,91.54,126019.0,251.0,0.462619,1205.276818,99.290773,97.919429,0.0,1314.41440
2018-04,2650.2050,167.787500,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,56.527619,85.68,205696.0,229.0,0.436053,1176.425238,100.354833,97.348429,0.0,1684.08900
2018-05,2706.3600,186.827500,2.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,62.424091,94.80,395656.0,938.0,0.436739,1155.392174,100.161182,96.953611,0.0,1657.07160
2018-06,2753.3120,188.162000,2.9,NaN,4.2,5.5,3.0,3.0,3.1,3.3,...,65.685714,73.54,136137.0,317.0,0.519750,1124.274286,99.746150,97.096810,0.0,1542.47075
2018-07,2795.4450,190.430000,2.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63.418095,98.24,58854.0,202.0,0.592273,1094.585909,99.979364,96.915524,NaN,1429.34675
2018-08,2859.9940,215.378000,2.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63.386522,91.53,195771.0,207.0,0.764348,1081.581739,101.161696,97.339217,NaN,1249.34000
2018-09,2905.0775,222.135000,2.3,NaN,3.4,4.3,3.2,1.8,2.0,2.5,...,66.864211,81.38,136694.0,202.0,0.653250,1056.427000,101.283684,97.154789,NaN,1137.45575
2018-10,2769.7925,220.502500,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63.803478,89.89,0.0,434.0,0.589783,1006.529565,101.139111,96.979636,NaN,1029.67650
2018-11,2726.6140,191.270000,2.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,60.775714,107.58,138892.0,453.0,0.490682,1009.740455,101.015364,97.239250,NaN,1106.70040
2018-12,2533.8475,160.232500,1.9,4.74,2.2,2.6,2.4,1.7,1.4,2.6,...,59.643684,122.80,0.0,257.0,0.491316,999.727619,100.985900,98.023000,NaN,928.01375
2019-01,2615.9175,153.782500,1.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,63.873333,126.96,135017.0,419.0,0.541429,1033.740000,101.090636,98.491095,NaN,902.52680
2019-02,2745.6700,170.080000,1.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.776842,102.87,67047.0,380.0,0.484750,1080.801000,101.029800,98.890526,NaN,830.12675
2019-03,2800.8700,183.000000,1.9,NaN,3.1,-0.3,2.1,0.8,1.6,1.1,...,67.538095,130.81,NaN,318.0,0.477857,1088.688571,100.838714,99.576524,NaN,965.49800
2019-04,2911.2650,201.007500,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,66.479048,NaN,65628.0,121.0,0.446316,1123.583182,100.737667,100.023667,NaN,1241.92800
2019-05,2852.9380,190.394000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.294091,NaN,NaN,NaN,0.381957,1056.733478,100.601650,100.386636,NaN,933.99080
2019-06,2878.2700,190.370000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,66.294000,NaN,NaN,NaN,0.273000,1044.200000,100.564750,101.287000,NaN,NaN

In [337]:
final = pd.read_csv(dir_to_csv)

In [338]:
final

,date_in_months,S&P 500 US,AAPLE US,CPI Index US,Big Mac Index US,GDP % Change US,Goods Index US,GDP Pers. Cons. US,GDP PIQQ Index,T. Gross Pr. Dom Invest. US,...,LNG US,LNG Export US,LNG China/US,Weapons X US,LNG AU Equity,Weapons NetTotal Return US,CHGDNU,KOHNPW,China Rice Imports Q/US,USDA Corn Export
0,1999-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.892045,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1099.76200
1,1999-07,1379.7880,1.885700,2.1,NaN,NaN,NaN,NaN,NaN,NaN,...,3.328125,5.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1065.90700
2,1999-08,1328.2125,2.126100,2.3,NaN,NaN,NaN,NaN,NaN,NaN,...,3.058241,5.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1102.00350
3,1999-09,1330.4200,2.614400,2.6,NaN,5.3,4.8,4.5,1.5,-0.5,...,2.734375,5.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1116.68380
4,1999-10,1306.1640,2.542160,2.6,NaN,NaN,NaN,NaN,NaN,NaN,...,2.373514,3.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,979.25925
5,1999-11,1401.2275,3.271750,2.6,NaN,NaN,NaN,NaN,NaN,NaN,...,1.375000,5.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,886.09500
6,1999-12,1439.7920,3.745080,2.7,NaN,7.0,7.0,5.4,2.1,1.3,...,1.000000,5.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,960.54400
7,2000-01,1427.0350,3.686400,2.7,NaN,NaN,NaN,NaN,NaN,NaN,...,1.696875,5.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,935.36675
8,2000-02,1372.7350,3.914050,3.2,NaN,NaN,NaN,NaN,NaN,NaN,...,2.387500,5.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,882.84350
9,2000-03,1458.9500,4.666060,3.8,NaN,1.5,6.1,6.4,2.8,2.4,...,2.164404,3.81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,859.22940
10,2000-04,1439.9700,4.344300,3.1,NaN,NaN,NaN,NaN,NaN,NaN,...,1.297700,5.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,915.10925
11,2000-05,1409.6400,3.581475,3.2,NaN,NaN,NaN,NaN,NaN,NaN,...,1.470177,5.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,858.28725
12,2000-06,1458.9500,3.483040,3.7,NaN,7.5,2.1,5.0,2.4,1.5,...,1.490059,3.79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,775.14180
13,2000-07,1472.2400,3.821425,3.7,NaN,NaN,NaN,NaN,NaN,NaN,...,1.490625,5.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,890.24775
14,2000-08,1483.2350,3.604900,3.4,NaN,NaN,NaN,NaN,NaN,NaN,...,1.562500,5.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1051.52020
15,2000-09,1473.2620,3.649800,3.5,NaN,0.5,4.2,3.8,2.5,1.7,...,1.579690,5.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1199.32125
16,2000-10,1389.9175,1.469875,3.4,NaN,NaN,NaN,NaN,NaN,NaN,...,1.111514,7.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,954.68375
17,2000-11,1375.5400,1.412950,3.4,NaN,NaN,NaN,NaN,NaN,NaN,...,0.978438,5.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,813.18260
18,2000-12,1324.7040,1.086620,3.4,2.38,2.5,3.5,3.5,2.1,0.7,...,1.154100,5.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,774.57800
19,2001-01,1328.5400,1.296875,3.7,NaN,NaN,NaN,NaN,NaN,NaN,...,1.151795,5.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,713.86975
20,2001-02,1302.9050,1.385050,3.5,NaN,NaN,NaN,NaN,NaN,NaN,...,1.465174,3.76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,888.75550
21,2001-03,1183.6580,1.488500,2.9,NaN,-1.1,0.9,2.0,2.6,0.2,...,1.404832,5.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,948.15340
22,2001-04,1201.9900,1.683025,3.3,NaN,NaN,NaN,NaN,NaN,NaN,...,1.248250,5.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,955.26175
23,2001-05,1270.5325,1.694450,3.6,NaN,NaN,NaN,NaN,NaN,NaN,...,1.198636,5.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,629.20300
24,2001-06,1237.9520,1.545140,3.2,NaN,2.4,1.1,0.9,2.7,1.1,...,1.064524,3.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,871.27975
25,2001-07,1205.7350,1.532500,2.7,NaN,NaN,NaN,NaN,NaN,NaN,...,0.983810,5.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1055.38625
26,2001-08,1176.9980,1.338720,2.7,NaN,NaN,NaN,NaN,NaN,NaN,...,0.883158,5.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1142.68940
27,2001-09,1046.2650,1.176625,2.6,NaN,-1.7,2.9,0.6,1.3,1.1,...,0.645000,5.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1050.81400
28,2001-10,1085.2800,1.270000,2.1,NaN,NaN,NaN,NaN,NaN,NaN,...,0.502727,7.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,819.15675
29,2001-11,1127.1900,1.391260,1.9,NaN,NaN,NaN,NaN,NaN,NaN,...,0.506190,5.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,758.40760
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,2017-01,2279.4050,119.725000,2.5,NaN,NaN,NaN,NaN,NaN,NaN,...,44.805000,51.34,130906.0,171.0,0.805250,879.515000,101.841444,NaN,0.0,959.89525
212,2017-02,2333.0050,133.395000,2.7,NaN,NaN,NaN,NaN,NaN,NaN,...,47.995263,52.04,67400.0,240.0,0.807750,919.767000,101.565333,NaN,0.0,1255.21300
213,2017-03,2368.1340,140.642000,2.4,NaN,1.8,1.9,1.7,2.0,1.0,...,45.696087,43.55,136914.0,183.0,0.673043,938.871304,101.255696,NaN,1.0,1486.16640
214,2017-04,2354.3450,142.577500,2.2,NaN,NaN,NaN,NaN,NaN,NaN,...,46.741053,50.67,65367.0,288.0,0.666176,953.296500,101.145111,NaN,0.0,1287.31325
215,2017-05,2396.9350,152.932500,1.9,NaN,NaN,NaN,NaN,NaN,NaN,...,48.099545,60.78,0.0,178.0,0.681957,988.126957,100.143500,NaN,0.0,1164.02325
216,2017-06,2433.1400,147.400000,1.6,NaN,3.0,5.6,1.7,1.2,2.0,...,48.134091,52.46,63076.0,400.0,0.611429,1003.840455,100.276455,NaN,2.0,1113.45380
217,2017-07,2457.2725,148.247500,1.7,NaN,NaN,NaN,NaN,NaN,NaN,...,46.754000,53.59,0.0,494.0,0.617381,1038.293333,100.609095,100.859000,1.0,1027.51925
218,2017-08,2446.6875,157.807500,1.9,NaN,NaN,NaN,NaN,NaN,NaN,...,42.453913,45.47,139423.0,224.0,0.563696,1069.774348,100.678478,101.212652,1.0,824.87360
219,2017-09,2491.9580,157.714000,2.2,NaN,2.8,4.1,1.4,2.2,1.9,...,43.633000,54.73,0.0,554.0,0.471667,1096.326667,100.491524,100.199000,3.0,749.90150
220,2017-10,2564.6950,157.897500,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,46.328182,80.19,259417.0,539.0,0.431364,1116.380909,100.174294,100.054619,0.0,516.60300
221,2017-11,2587.8525,173.072500,2.2,NaN,NaN,NaN,NaN,NaN,NaN,...,48.666667,80.10,407325.0,376.0,0.471818,1138.683636,99.667818,100.031000,1.0,558.10040
222,2017-12,2665.2960,171.726000,2.1,4.47,2.3,6.8,2.6,2.5,1.3,...,49.880000,82.60,259262.0,455.0,0.430263,1131.860000,99.316095,99.715600,0.0,675.52575
223,2018-01,2803.1400,175.515000,2.1,NaN,NaN,NaN,NaN,NaN,NaN,...,55.990000,72.46,506485.0,291.0,0.565238,1229.062609,99.241409,99.203143,4.0,802.19900
224,2018-02,2715.3000,166.210000,2.2,NaN,NaN,NaN,NaN,NaN,NaN,...,56.116842,73.68,255101.0,199.0,0.497000,1203.389500,99.383267,98.346526,0.0,1049.93000
225,2018-03,2691.7920,173.386000,2.4,NaN,2.2,-0.6,1.0,2.0,2.5,...,53.247619,91.54,126019.0,251.0,0.462619,1205.276818,99.290773,97.919429,0.0,1314.41440
226,2018-04,2650.2050,167.787500,2.5,NaN,NaN,NaN,NaN,NaN,NaN,...,56.527619,85.68,205696.0,229.0,0.436053,1176.425238,100.354833,97.348429,0.0,1684.08900
227,2018-05,2706.3600,186.827500,2.8,NaN,NaN,NaN,NaN,NaN,NaN,...,62.424091,94.80,395656.0,938.0,0.436739,1155.392174,100.161182,96.953611,0.0,1657.07160
228,2018-06,2753.3120,188.162000,2.9,NaN,4.2,5.5,3.0,3.0,3.1,...,65.685714,73.54,136137.0,317.0,0.519750,1124.274286,99.746150,97.096810,0.0,1542.47075
229,2018-07,2795.4450,190.430000,2.9,NaN,NaN,NaN,NaN,NaN,NaN,...,63.418095,98.24,58854.0,202.0,0.592273,1094.585909,99.979364,96.915524,NaN,1429.34675
230,2018-08,2859.9940,215.378000,2.7,NaN,NaN,NaN,NaN,NaN,NaN,...,63.386522,91.53,195771.0,207.0,0.764348,1081.581739,101.161696,97.339217,NaN,1249.34000
231,2018-09,2905.0775,222.135000,2.3,NaN,3.4,4.3,3.2,1.8,2.0,...,66.864211,81.38,136694.0,202.0,0.653250,1056.427000,101.283684,97.154789,NaN,1137.45575
232,2018-10,2769.7925,220.502500,2.5,NaN,NaN,NaN,NaN,NaN,NaN,...,63.803478,89.89,0.0,434.0,0.589783,1006.529565,101.139111,96.979636,NaN,1029.67650
233,2018-11,2726.6140,191.270000,2.2,NaN,NaN,NaN,NaN,NaN,NaN,...,60.775714,107.58,138892.0,453.0,0.490682,1009.740455,101.015364,97.239250,NaN,1106.70040
234,2018-12,2533.8475,160.232500,1.9,4.74,2.2,2.6,2.4,1.7,1.4,...,59.643684,122.80,0.0,257.0,0.491316,999.727619,100.985900,98.023000,NaN,928.01375
235,2019-01,2615.9175,153.782500,1.6,NaN,NaN,NaN,NaN,NaN,NaN,...,63.873333,126.96,135017.0,419.0,0.541429,1033.740000,101.090636,98.491095,NaN,902.52680
236,2019-02,2745.6700,170.080000,1.5,NaN,NaN,NaN,NaN,NaN,NaN,...,65.776842,102.87,67047.0,380.0,0.484750,1080.801000,101.029800,98.890526,NaN,830.12675
237,2019-03,2800.8700,183.000000,1.9,NaN,3.1,-0.3,2.1,0.8,1.6,...,67.538095,130.81,NaN,318.0,0.477857,1088.688571,100.838714,99.576524,NaN,965.49800
238,2019-04,2911.2650,201.007500,2.0,NaN,NaN,NaN,NaN,NaN,NaN,...,66.479048,NaN,65628.0,121.0,0.446316,1123.583182,100.737667,100.023667,NaN,1241.92800
239,2019-05,2852.9380,190.394000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65.294091,NaN,NaN,NaN,0.381957,1056.733478,100.601650,100.386636,NaN,933.99080
240,2019-06,2878.2700,190.370000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,66.294000,NaN,NaN,NaN,0.273000,1044.200000,100.564750,101.287000,NaN,NaN